apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-api
  namespace: school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-api
  template:
    metadata:
      labels:
        app: school-api
    spec:
      containers:
        - name: school-api
          image: schoolregistrybamoy.azurecr.io/school-api:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: school-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: school-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: school-config
                  key: DB_NAME
            - name: DB_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: school-config
                  key: DB_SSLMODE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "school-kv-secrets"