apiVersion: v1
kind: Service
metadata:
  name: school-front-service
  namespace: school
spec:
  selector:
    app: school-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer