apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: school-kv-secrets
  namespace: school
spec:
  provider: azure
  secretObjects:
    - secretName: school-secret
      type: Opaque
      data:
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2f7f0ba8-8540-4465-a789-59fe5393ddfa"
    keyvaultName: "school-kv"
    tenantId: "c371d4f5-b34f-4b06-9e66-517fed904220"
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret